# Generated by Django 3.2 on 2021-06-11 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=38, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stolperstein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('deathdate', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=100, null=True)),
                ('deathplace', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_for_persecution', models.CharField(choices=[('JEWISH', 'jewish religion'), ('POLITICAL', 'political persecution'), ('HOMOSEXUAL', 'homosexual orientation'), ('OTHER', 'other'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=10)),
                ('info_text', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stolpersteine', to='api.location')),
            ],
            options={
                'unique_together': {('name', 'location')},
            },
        ),
        migrations.CreateModel(
            name='LifeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=38)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('stolperstein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stolperstein', to='api.stolperstein')),
            ],
        ),
    ]
