# Generated by Django 3.2 on 2021-06-17 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stolperstein',
            name='family_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lifestation',
            name='stolperstein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_stations', to='api.stolperstein'),
        ),
    ]
