# Generated by Django 3.2 on 2023-08-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationreference',
            name='test',
        ),
    ]
