# Generated by Django 3.2 on 2023-10-01 13:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_locationreference_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfiles',
            name='video',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='customfiles',
            name='videoName',
            field=models.CharField(blank=True, db_column='video_name', default=None, max_length=100, null=True),
        ),
    ]
