# Generated by Django 3.2 on 2023-10-01 13:42

from django.db import migrations

def rename_columns(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    CustomFile = apps.get_model('api', 'CustomFiles')

    # Use the correct database column names for your specific case.
    # For example, if your columns are 'photoname', 'audioname', and 'videoname':
    sql = """
    ALTER TABLE api_customfiles
    RENAME COLUMN photoname TO photo_name;
    ALTER TABLE api_customfiles
    RENAME COLUMN audioname TO audio_name;
    """

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231001_1529'),
    ]

    operations = [
        migrations.RunPython(rename_columns),
    ]
