# Generated by Django 3.2 on 2021-06-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210619_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stolperstein',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.stolperstein'),
        ),
    ]
