# Generated by Django 3.2 on 2023-10-14 13:24

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231001_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfiles',
            name='audioName',
            field=models.CharField(blank=True, db_column='audio_name', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customfiles',
            name='photoName',
            field=models.CharField(blank=True, db_column='photo_name', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customfiles',
            name='video',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/%Y%m%d/'),
        ),
    ]
