# Generated by Django 3.2 on 2021-06-21 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_order_stolperstein'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='responsible_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
