# Generated by Django 3.2 on 2021-06-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210621_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stolperstein',
            options={'ordering': ['location', 'order__position']},
        ),
    ]
