# Generated by Django 3.2 on 2023-10-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20231015_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfiles',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
