# Generated by Django 3.2 on 2021-06-23 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_stolperstein_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StolpersteinRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('FAMILY', 'family member'), ('WORK', 'work colleague'), ('FRIEND', 'friend'), ('NEIGHBOUR', 'neighbour'), ('COMMUNITY', 'community'), ('OTHER', 'other')], max_length=10)),
                ('related_stolperstein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stolperstein')),
                ('stolperstein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedStolperstein', to='api.stolperstein')),
            ],
        ),
    ]
