# Generated by Django 3.2 on 2022-01-13 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20210623_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='lifestation',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='LocationReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=38)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('responsible_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
