# Generated by Django 3.2 on 2022-01-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220113_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('audioName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('audio', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageFile',
        ),
        migrations.RemoveField(
            model_name='stolperstein',
            name='photo',
        ),
        migrations.AddField(
            model_name='customfiles',
            name='stolperstein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.stolperstein'),
        ),
    ]
