# Generated by Django 3.2 on 2022-01-16 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220116_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfiles',
            name='stolperstein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stolperstein'),
        ),
    ]
