# Generated by Django 3.2 on 2023-11-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20231110_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourlocation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
