# Generated by Django 3.2 on 2023-11-21 08:03

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20231112_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourlocation',
            name='audio',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='audios/%Y%m%d/'),
        ),
    ]
