# Generated by Django 3.2 on 2023-11-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_tourlocation_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourlocation',
            name='audioName',
            field=models.CharField(blank=True, db_column='audio_name', default=None, max_length=100, null=True),
        ),
    ]
