# Generated by Django 3.2 on 2022-01-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_customfiles_stolperstein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfiles',
            name='audio',
            field=models.FileField(null=True, upload_to='audios/%Y/%m/%d/'),
        ),
    ]
