# Generated by Django 3.2 on 2022-01-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_customfiles_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('stolperstein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_textboxes', to='api.stolperstein')),
            ],
        ),
    ]
