# Generated by Django 3.2 on 2023-08-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_customfiles_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationreference',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
